# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1segg6FK0OgsHWlAfFakeiO8BRqOL3m8G

**Olabosipo Ibirogba, Ph.D**

**Healthcare Insurance Billing Analytics Project**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# load data

df = pd.read_csv('/patients_data.csv')

# standardize column names by removing spaces, converting to lowercase, and replacing spaces with underscores
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df

# extract states from the provider address column
df['state'] = df['provider_address'].str.split(',').str[2].str.strip()

# Rename column
df.rename(columns={'healthcare_provider': 'healthcare_provider_bill'}, inplace=True)
df
files.download('/content/df.csv')

"""EDA Deep Dive"""

# -----------------------------
# 3. Convert data types
# -----------------------------
date_cols = ['admission_date', 'discharge_date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

numeric_cols = ['patients_charges', 'patients_oop', 'healthcare_provider_bill', 'duration']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Optional: clean state
if 'state' in df.columns:
    df['state'] = df['state'].astype(str).str.strip().str.upper()

# -----------------------------
# 4. Basic overview
# -----------------------------
print("\nShape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)


# =========================================================
# CHECK 1: DRG vs Patients Charges Integrity
# =========================================================
print("\n" + "="*60)
print("CHECK 1: DRG vs Patients Charges Integrity")
print("="*60)

drg_charge_variance = (
    df.groupby('drg_definition', dropna=False)
      .agg(
          record_count=('patients_charges', 'count'),
          min_charge=('patients_charges', 'min'),
          max_charge=('patients_charges', 'max'),
          mean_charge=('patients_charges', 'mean'),
          std_charge=('patients_charges', 'std'),
          unique_charge_count=('patients_charges', 'nunique')
      )
      .reset_index()
)

drg_charge_variance['charge_range'] = (
    drg_charge_variance['max_charge'] - drg_charge_variance['min_charge']
)

# Coefficient of variation
drg_charge_variance['cv'] = (
    drg_charge_variance['std_charge'] / drg_charge_variance['mean_charge']
)

print("\nTop DRGs by charge variance:")
print(
    drg_charge_variance.sort_values('charge_range', ascending=False)
    .head(10)
)

# Flag DRGs with unusually large within-DRG variation
high_variance_drg = drg_charge_variance[
    (drg_charge_variance['record_count'] >= 5) &
    (
        (drg_charge_variance['cv'] > 0.5) |
        (drg_charge_variance['charge_range'] > drg_charge_variance['charge_range'].quantile(0.95))
    )
].sort_values('charge_range', ascending=False)

print("\nFlagged DRGs with high charge variation:")
print(high_variance_drg.head(20))


# =========================================================
# CHECK 2: Date Logic & Chronology
# =========================================================
print("\n" + "="*60)
print("CHECK 2: Date Logic & Chronology")
print("="*60)

# Calculate actual duration from dates
df['calculated_duration'] = (df['discharge_date'] - df['admission_date']).dt.days

# Flag issues
df['negative_duration_flag'] = df['calculated_duration'] < 0
df['duration_mismatch_flag'] = df['duration'] != df['calculated_duration']
df['extreme_stay_flag'] = df['calculated_duration'] > 500

date_issue_df = df[
    df['negative_duration_flag'] |
    df['duration_mismatch_flag'] |
    df['extreme_stay_flag'] |
    df['admission_date'].isna() |
    df['discharge_date'].isna()
].copy()

print("\nSummary of chronology checks:")
print("Negative durations:", df['negative_duration_flag'].sum())
print("Duration mismatches:", df['duration_mismatch_flag'].sum())
print("Extreme stays > 500 days:", df['extreme_stay_flag'].sum())
print("Missing admission/discharge dates:", df['admission_date'].isna().sum() + df['discharge_date'].isna().sum())

print("\nSample flagged records:")
print(
    date_issue_df[
        ['provider_id', 'provider_name', 'admission_date', 'discharge_date', 'duration',
         'calculated_duration', 'negative_duration_flag', 'duration_mismatch_flag', 'extreme_stay_flag']
    ].head(20)
)


# =========================================================
# CHECK 3: OOP vs Total Charges Ratio
# =========================================================
print("\n" + "="*60)
print("CHECK 3: OOP vs Total Charges Ratio")
print("="*60)

# Avoid division by zero
df['patient_responsibility_pct'] = np.where(
    df['patients_charges'] > 0,
    (df['patients_oop'] / df['patients_charges']) * 100,
    np.nan
)

# Flags
df['oop_gt_total_flag'] = df['patients_oop'] > df['patients_charges']
df['negative_oop_flag'] = df['patients_oop'] < 0
df['negative_charge_flag'] = df['patients_charges'] < 0

print("\nPatient responsibility summary (%):")
print(df['patient_responsibility_pct'].describe())

print("\nPotential financial data issues:")
print("OOP > Total Charges:", df['oop_gt_total_flag'].sum())
print("Negative OOP:", df['negative_oop_flag'].sum())
print("Negative Charges:", df['negative_charge_flag'].sum())

print("\nResponsibility percentage buckets:")
bins = [-np.inf, 0, 10, 20, 50, 100, np.inf]
labels = ['<0%', '0-10%', '10-20%', '20-50%', '50-100%', '>100%']
df['oop_ratio_bucket'] = pd.cut(df['patient_responsibility_pct'], bins=bins, labels=labels)

print(df['oop_ratio_bucket'].value_counts(dropna=False))

print("\nSample flagged OOP records:")
print(
    df.loc[
        df['oop_gt_total_flag'] | df['negative_oop_flag'] | df['negative_charge_flag'],
        ['provider_id', 'provider_name', 'patients_charges', 'patients_oop', 'patient_responsibility_pct']
    ].head(20)
)


# =========================================================
# CHECK 4: Provider Mapping
# =========================================================
print("\n" + "="*60)
print("CHECK 4: Provider Mapping")
print("="*60)

provider_region_check = (
    df.groupby('provider_id', dropna=False)
      .agg(
          provider_name_count=('provider_name', 'nunique'),
          region_count=('hospital_referral_region_description', 'nunique')
      )
      .reset_index()
)

multi_region_provider = provider_region_check[provider_region_check['region_count'] > 1]

print("\nProviders mapped to multiple referral regions:")
print("Count:", len(multi_region_provider))
print(multi_region_provider.head(20))

if len(multi_region_provider) > 0:
    print("\nDetailed mapping for flagged providers:")
    flagged_provider_ids = multi_region_provider['provider_id'].head(20).tolist()
    detailed_mapping = (
        df[df['provider_id'].isin(flagged_provider_ids)]
        [['provider_id', 'provider_name', 'hospital_referral_region_description', 'state']]
        .drop_duplicates()
        .sort_values(['provider_id', 'hospital_referral_region_description'])
    )
    print(detailed_mapping)


# =========================================================
# CHECK 5: Completeness of Description
# =========================================================
print("\n" + "="*60)
print("CHECK 5: Completeness of Description")
print("="*60)

description_null_count = df['drg_definition'].isna().sum()
description_blank_count = (
    df['drg_definition']
    .astype(str)
    .str.strip()
    .eq('')
    .sum()
)

print("\nDRG Definition completeness:")
print("Null values:", description_null_count)
print("Blank values:", description_blank_count)
print("Completeness %:", round((1 - ((description_null_count + description_blank_count) / len(df))) * 100, 2))

print("\nSample missing/blank DRG Definition rows:")
print(
    df.loc[
        df['drg_definition'].isna() | df['drg_definition'].astype(str).str.strip().eq(''),
        ['provider_id', 'provider_name', 'drg_definition', 'patients_charges']
    ].head(20)
)


# =========================================================
# OPTIONAL: Export flagged outputs
# =========================================================
drg_charge_variance.to_csv('/content/drg_charge_variance_check.csv', index=False)
date_issue_df.to_csv('/content/date_logic_issues.csv', index=False)
provider_region_check.to_csv('/content/provider_region_check.csv', index=False)

print("\nSaved output files:")
print("- /content/drg_charge_variance_check.csv")
print("- /content/date_logic_issues.csv")
print("- /content/provider_region_check.csv")

from google.colab import files

# Q1. Cost-to-Charge ratio by DRG
# =========================================================
# Assuming patients_oop is actual paid/billed by patient portion
drg_financials = (
    df.groupby('drg_definition', dropna=False)
      .agg(
          total_gross_charges=('patients_charges', 'sum'),
          total_oop_paid=('patients_oop', 'sum'),
          avg_gross_charge=('patients_charges', 'mean'),
          avg_oop_paid=('patients_oop', 'mean'),
          case_count=('drg_definition', 'count')
      )
      .reset_index()
)

drg_financials['cost_to_charge_ratio'] = np.where(
    drg_financials['total_gross_charges'] > 0,
    drg_financials['total_oop_paid'] / drg_financials['total_gross_charges'],
    np.nan
)

print("\nQ1: DRG Cost-to-Charge Ratio")
print(drg_financials.sort_values('total_gross_charges', ascending=False).head(10))

print("\nTop DRGs by highest cost-to-charge ratio:")
print(drg_financials.sort_values('cost_to_charge_ratio', ascending=False).head(10))


# =========================================================
# Q2. Providers with highest average OOP
# =========================================================
provider_oop = (
    df.groupby(['provider_id', 'provider_name'], dropna=False)
      .agg(
          avg_oop=('patients_oop', 'mean'),
          total_oop=('patients_oop', 'sum'),
          avg_charge=('patients_charges', 'mean'),
          case_count=('provider_id', 'count')
      )
      .reset_index()
      .sort_values('avg_oop', ascending=False)
)

print("\nQ2: Providers with Highest Average OOP")
print(provider_oop.head(10))


# =========================================================
# Q3. Correlation between Duration and Patient Charges
# =========================================================
duration_charge_df = df[['duration', 'patients_charges', 'drg_definition']].dropna()

correlation = duration_charge_df['duration'].corr(duration_charge_df['patients_charges'])

print("\nQ3: Correlation between Duration and Patient Charges")
print("Overall correlation:", correlation)

# DRG-level duration vs charge relationship
drg_duration_charge = (
    duration_charge_df.groupby('drg_definition')
    .agg(
        avg_duration=('duration', 'mean'),
        avg_charge=('patients_charges', 'mean'),
        case_count=('drg_definition', 'count')
    )
    .reset_index()
)

print("\nAverage duration and charge by DRG:")
print(drg_duration_charge.sort_values('avg_duration', ascending=False).head(10))


# =========================================================
# Q4. Geographic leakage by region for same DRG
# =========================================================
region_drg_charges = (
    df.groupby(['hospital_referral_region_description', 'drg_definition'], dropna=False)
      .agg(
          avg_charge=('patients_charges', 'mean'),
          total_charge=('patients_charges', 'sum'),
          case_count=('drg_definition', 'count')
      )
      .reset_index()
)

# Compare DRG avg charge across regions
drg_region_variation = (
    region_drg_charges.groupby('drg_definition')
    .agg(
        min_region_avg_charge=('avg_charge', 'min'),
        max_region_avg_charge=('avg_charge', 'max'),
        overall_avg_charge=('avg_charge', 'mean'),
        region_count=('hospital_referral_region_description', 'nunique')
    )
    .reset_index()
)

drg_region_variation['regional_charge_gap'] = (
    drg_region_variation['max_region_avg_charge'] - drg_region_variation['min_region_avg_charge']
)

print("\nQ4: Geographic Leakage - DRGs with Largest Regional Charge Gap")
print(drg_region_variation.sort_values('regional_charge_gap', ascending=False).head(10))


# =========================================================
# Q5. Revenue Velocity - Month-over-Month Billing Volume
# =========================================================
df['discharge_month'] = df['discharge_date'].dt.to_period('M').astype(str)

monthly_revenue = (
    df.groupby('discharge_month', dropna=False)
      .agg(
          total_charges=('patients_charges', 'sum'),
          total_oop=('patients_oop', 'sum'),
          billing_volume=('discharge_month', 'count')
      )
      .reset_index()
      .sort_values('discharge_month')
)

monthly_revenue['mom_charge_growth_pct'] = monthly_revenue['total_charges'].pct_change() * 100
monthly_revenue['mom_volume_growth_pct'] = monthly_revenue['billing_volume'].pct_change() * 100

print("\nQ5: Revenue Velocity - Month-over-Month")
print(monthly_revenue.head(12))


# =========================================================
# Optional exports
# =========================================================
drg_financials.to_csv('/content/drg_financials.csv', index=False)
provider_oop.to_csv('/content/provider_oop_analysis.csv', index=False)
drg_duration_charge.to_csv('/content/drg_duration_charge.csv', index=False)
drg_region_variation.to_csv('/content/drg_region_variation.csv', index=False)
monthly_revenue.to_csv('/content/monthly_revenue_velocity.csv', index=False)
df.to_csv('/content/df.csv', index=False)

print("\nFiles saved:")
print("/content/drg_financials.csv")
print("/content/provider_oop_analysis.csv")
print("/content/drg_duration_charge.csv")
print("/content/drg_region_variation.csv")
print("/content/monthly_revenue_velocity.csv")

files.download('/content/provider_oop_analysis.csv')
files.download('/content/drg_duration_charge.csv')
files.download('/content/drg_region_variation.csv')
files.download('/content/monthly_revenue_velocity.csv')
files.download('/content/df.csv')

# 4. Financial Normalization
# -----------------------------
# Avoid divide-by-zero issues
df['avg_charge_per_day'] = np.where(
    df['duration'] > 0,
    df['patients_charges'] / df['duration'],
    np.nan
)

print("\nFinancial Normalization: Average Charge per Day")
print(df[['provider_name', 'drg_definition', 'patients_charges', 'duration', 'avg_charge_per_day']].head())


# =========================================================
# 5. Segmentation Analysis
# Top 10 drivers of total spend by DRG and Provider
# =========================================================
top_spend_drivers = (
    df.groupby(['drg_definition', 'provider_name'], dropna=False)
      .agg(
          total_spend=('patients_charges', 'sum'),
          avg_charge=('patients_charges', 'mean'),
          avg_oop=('patients_oop', 'mean'),
          case_count=('drg_definition', 'count')
      )
      .reset_index()
      .sort_values('total_spend', ascending=False)
)

top_10_spend_drivers = top_spend_drivers.head(10)

print("\nTop 10 Drivers of Total Spend")
print(top_10_spend_drivers)


# =========================================================
# 6. Variance Analysis
# Standard deviation of charges within each DRG
# =========================================================
drg_variance = (
    df.groupby('drg_definition', dropna=False)
      .agg(
          avg_charge=('patients_charges', 'mean'),
          std_charge=('patients_charges', 'std'),
          min_charge=('patients_charges', 'min'),
          max_charge=('patients_charges', 'max'),
          case_count=('drg_definition', 'count')
      )
      .reset_index()
)

drg_variance['charge_range'] = drg_variance['max_charge'] - drg_variance['min_charge']

print("\nDRG Variance Analysis")
print(drg_variance.sort_values('std_charge', ascending=False).head(10))


# =========================================================
# 7. Geographic Benchmarking
# By Provider Zip Code and Referral Region
# =========================================================
zip_benchmark = (
    df.groupby('provider_zip_code', dropna=False)
      .agg(
          total_charges=('patients_charges', 'sum'),
          avg_charge=('patients_charges', 'mean'),
          avg_oop=('patients_oop', 'mean'),
          avg_charge_per_day=('avg_charge_per_day', 'mean'),
          case_count=('provider_zip_code', 'count')
      )
      .reset_index()
      .sort_values('avg_charge', ascending=False)
)

region_benchmark = (
    df.groupby('hospital_referral_region_description', dropna=False)
      .agg(
          total_charges=('patients_charges', 'sum'),
          avg_charge=('patients_charges', 'mean'),
          avg_oop=('patients_oop', 'mean'),
          avg_charge_per_day=('avg_charge_per_day', 'mean'),
          case_count=('hospital_referral_region_description', 'count')
      )
      .reset_index()
      .sort_values('avg_charge', ascending=False)
)

print("\nTop Expensive Zip Codes")
print(zip_benchmark.head(10))

print("\nTop Expensive Hospital Referral Regions")
print(region_benchmark.head(10))


# =========================================================
# 8. Time-Series Analysis
# Seasonal peaks in billing using admission date
# =========================================================
df['admission_month'] = df['admission_date'].dt.to_period('M').astype(str)
df['admission_year'] = df['admission_date'].dt.year
df['admission_month_num'] = df['admission_date'].dt.month

monthly_billing = (
    df.groupby('admission_month', dropna=False)
      .agg(
          total_charges=('patients_charges', 'sum'),
          total_oop=('patients_oop', 'sum'),
          billing_volume=('admission_month', 'count')
      )
      .reset_index()
      .sort_values('admission_month')
)

seasonality = (
    df.groupby('admission_month_num', dropna=False)
      .agg(
          avg_monthly_charges=('patients_charges', 'mean'),
          total_charges=('patients_charges', 'sum'),
          avg_oop=('patients_oop', 'mean'),
          case_count=('admission_month_num', 'count')
      )
      .reset_index()
      .sort_values('admission_month_num')
)

print("\nMonthly Billing Trend")
print(monthly_billing.head(12))

print("\nSeasonality by Admission Month")
print(seasonality)


# =========================================================
# 9. Optional simple forecast prep dataset
# =========================================================
forecast_df = monthly_billing.copy()
forecast_df['admission_month'] = pd.to_datetime(forecast_df['admission_month'])

print("\nForecast-ready dataset:")
print(forecast_df.head())


# =========================================================
# 10. Export outputs
# =========================================================
top_spend_drivers.to_csv('/content/top_spend_drivers.csv', index=False)
drg_variance.to_csv('/content/drg_variance_analysis.csv', index=False)
zip_benchmark.to_csv('/content/zip_benchmark.csv', index=False)
region_benchmark.to_csv('/content/region_benchmark.csv', index=False)
monthly_billing.to_csv('/content/monthly_billing_trend.csv', index=False)
seasonality.to_csv('/content/seasonality_analysis.csv', index=False)

print("\nFiles saved:")
print("/content/top_spend_drivers.csv")
print("/content/drg_variance_analysis.csv")
print("/content/zip_benchmark.csv")
print("/content/region_benchmark.csv")
print("/content/monthly_billing_trend.csv")
print("/content/seasonality_analysis.csv")

files.download('/content/top_spend_drivers.csv')
files.download('/content/drg_variance_analysis.csv')
files.download('/content/zip_benchmark.csv')
files.download('/content/region_benchmark.csv')
files.download('/content/monthly_billing_trend.csv')
files.download('/content/seasonality_analysis.csv')

bubble_df = (
    df.groupby(['provider_name', 'drg_definition'], as_index=False)
      .agg(
          avg_duration=('duration', 'mean'),
          avg_charge=('patients_charges', 'mean'),
          total_oop=('patients_oop', 'sum'),
          case_count=('provider_name', 'count')
      )
)

# keep only top spend groups so chart is readable
bubble_df = bubble_df.sort_values('avg_charge', ascending=False).head(40)

plt.figure(figsize=(10, 6))
plt.scatter(
    bubble_df['avg_duration'],
    bubble_df['avg_charge'],
    s=bubble_df['total_oop'] / 500,
    alpha=0.6
)
plt.xlabel('Average Duration')
plt.ylabel('Average Patient Charges')
plt.title('High-Cost, High-Stay Outliers by Provider-DRG Group')
plt.grid(True)
plt.show()


# =========================
# 2. Better Heat Map
# Use top DRGs and top regions only
# =========================
top_drgs = df.groupby('drg_definition')['patients_charges'].sum().nlargest(10).index
top_regions = df.groupby('hospital_referral_region_description')['patients_charges'].sum().nlargest(10).index

heat_df = df[
    df['drg_definition'].isin(top_drgs) &
    df['hospital_referral_region_description'].isin(top_regions)
]

heat_table = (
    heat_df.groupby(['hospital_referral_region_description', 'drg_definition'])['patients_charges']
    .sum()
    .unstack(fill_value=0)
)

plt.figure(figsize=(12, 7))
plt.imshow(heat_table, aspect='auto')
plt.colorbar(label='Total Charges')
plt.xticks(range(len(heat_table.columns)), heat_table.columns, rotation=45, ha='right')
plt.yticks(range(len(heat_table.index)), heat_table.index)
plt.title('Top 10 Regions vs Top 10 DRGs by Total Charges')
plt.tight_layout()
plt.show()


# =========================
# 3. Better Box Plot
# Show only top 5 providers by volume
# =========================
top5_providers = df.groupby('provider_name').size().nlargest(5).index
box_df = df[df['provider_name'].isin(top5_providers)]

box_data = [box_df.loc[box_df['provider_name'] == p, 'patients_charges'] for p in top5_providers]

plt.figure(figsize=(10, 6))
plt.boxplot(box_data, tick_labels=top5_providers, showfliers=False)
plt.xticks(rotation=30, ha='right')
plt.ylabel('Patients Charges')
plt.title('Billing Spread Across Top 5 Providers')
plt.tight_layout()
plt.show()


# =========================
# 4. Better Dual-Axis Line Chart
# Use monthly totals
# =========================
df['admission_month'] = df['admission_date'].dt.to_period('M').astype(str)

monthly = (
    df.groupby('admission_month', as_index=False)
      .agg(
          total_charges=('patients_charges', 'sum'),
          patient_volume=('provider_id', 'count')
      )
      .sort_values('admission_month')
)

fig, ax1 = plt.subplots(figsize=(11, 6))

line1, = ax1.plot(monthly['admission_month'], monthly['total_charges'], marker='o', color='red', label = 'Total Charges')
ax1.set_ylabel('Total Charges')
ax1.set_xlabel('Admission Month')
ax1.tick_params(axis='x', rotation=45)

ax2 = ax1.twinx()
line2, = ax2.plot(monthly['admission_month'], monthly['patient_volume'], marker='s', color='blue', label = 'Patient Volume')
ax2.set_ylabel('Patient Volume')

# Combine legends
lines = [line1, line2]
labels = [line.get_label() for line in lines]
ax1.legend(lines, labels, loc='upper left')


plt.title('Monthly Charges vs Patient Volume')
plt.tight_layout()
plt.show()


# =========================
# 5. Better Stacked Bar Chart
# Top 8 providers + top 5 DRGs
# =========================
top8_providers = df.groupby('provider_name')['patients_charges'].sum().nlargest(8).index
top5_drgs = df.groupby('drg_definition')['patients_charges'].sum().nlargest(5).index

stack_df = df[
    df['provider_name'].isin(top8_providers) &
    df['drg_definition'].isin(top5_drgs)
]

stack_table = (
    stack_df.groupby(['provider_name', 'drg_definition'])['patients_charges']
    .sum()
    .unstack(fill_value=0)
)

stack_table.plot(kind='bar', stacked=True, figsize=(12, 7))
plt.xlabel('Provider')
plt.ylabel('Total Charges')
plt.title('Top Providers by Charge Mix Across Top DRGs')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()